name: Sync to Hugging Face Hub

on:
  push:
    branches:
      - master
  workflow_dispatch: # Allows manual trigger from GitHub Actions tab

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          
      - name: Install dependencies and pytest
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          
      - name: Run Tests
        run: pytest
          
      - name: Push to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add huggingface https://moulsai2296:$HF_TOKEN@huggingface.co/spaces/moulisai2296/pizzaflow_v2
          git push --force huggingface master:main
